// categoryTypes
export const FETCH_CATEGORIES="FETCH_CATEGORIES"
export const FETCH_SOCIAL_HANDLES="FETCH_SOCIAL_HANDLES"
export const FETCH_POLICY="FETCH_POLICY"
export const ADD_CATEGORY="ADD_CATEGORY"
export const SECTION_LOADER="SECTION_LOADER"